apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "staging-observability-vm-stack"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "observability"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  sources:
    -
      repoURL: "https://victoriametrics.github.io/helm-charts/"
      chart: "victoria-metrics-k8s-stack"
      targetRevision: "*"
      helm:
        valueFiles:
          - "$values/../../deploy/observability/victoria-metrics-k8s-stack-values.yaml"
          - "$values/gitops/environments/staging/values/vm-stack-values.yaml"
    -
      repoURL: "git@github.com:mstrugarevic1/eks-argocd-platform-boilerplate.git"
      targetRevision: "main"
      ref: "values"
