clusterName: "my-platform-production"
region: "us-east-1"
vpcId: "VPC_ID"
serviceAccount:
  create: true
  name: "aws-load-balancer-controller"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/my-platform-production-alb-controller"
