version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directories:
      - /terraform/stack
      - /terraform/foundation
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: /app
    schedule:
      interval: monthly
