apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "dev-aws-load-balancer-controller"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kube-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    -
      repoURL: "https://aws.github.io/eks-charts"
      chart: "aws-load-balancer-controller"
      targetRevision: "1.9.2"
      helm:
        valueFiles:
          - "$values/gitops/environments/dev/values/aws-load-balancer-controller-values.yaml"
    -
      repoURL: "git@github.com:mstrugarevic1/aws-eks-gitops-platform.git"
      targetRevision: "main"
      ref: "values"
