apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "dev-metrics-server"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kube-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    -
      repoURL: "https://kubernetes-sigs.github.io/metrics-server/"
      chart: "metrics-server"
      targetRevision: "3.13.1"
    -
      repoURL: "git@github.com:mstrugarevic1/aws-eks-gitops-platform.git"
      targetRevision: "main"
      ref: "values"
