apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
