apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "example-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
