apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "production-external-secrets"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "external-secrets"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  sources:
    -
      repoURL: "https://charts.external-secrets.io"
      chart: "external-secrets"
      targetRevision: "2.7.0"
      helm:
        valueFiles:
          - "$values/gitops/environments/production/values/external-secrets-values.yaml"
    -
      repoURL: "git@github.com:mstrugarevic1/eks-gitops-platform.git"
      targetRevision: "main"
      ref: "values"
