apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "production-observability-promtail"
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "observability"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  sources:
    -
      repoURL: "https://grafana.github.io/helm-charts"
      chart: "promtail"
      targetRevision: "*"
      helm:
        valueFiles:
          - "$values/../../deploy/observability/promtail-values.yaml"
    -
      repoURL: "git@github.com:mstrugarevic1/eks-argocd-platform-boilerplate.git"
      targetRevision: "main"
      ref: "values"
