apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "dev-root"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  source:
    repoURL: "git@github.com:mstrugarevic1/aws-eks-gitops-platform.git"
    targetRevision: "main"
    path: "gitops/environments/dev/apps"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
